###
# app configuration
# http://docs.pylonsproject.org/projects/pyramid/en/1.5-branch/narr/environment.html
###

[app:main]
use = egg:camtasia_request

pyramid.reload_templates = true
pyramid.debug_authorization = false
pyramid.debug_notfound = false
pyramid.debug_routematch = false
pyramid.default_locale_name = en
pyramid.includes = 
    pyramid_debugtoolbar

mail.host = smtp.gmail.com
mail.port = 465
mail.username = eportfolio@uwosh.edu
mail.password = uwosh eportfolio 2014
# mail.tls =
mail.ssl = True
# mail.keyfile = 
# mail.certfile = 
mail.default_sender = eportfolio@uwosh.edu
# mail.debug = 

###
# Application configuration variables
###

WTF_CSRF_ENABLED = True

# provided by D2L from keytool
# BETA
APP_ID = PkThAwhB0a3Xg6R2SjVugg
# PRODUCTION
# APP_ID = _KWYXlSPgRLiAr-Ye6UpcQ

# provided by D2L from keytool
# BETA
APP_KEY = hrzc1K0SZ_Co1T5jV26EAw
# PRODUCTION
# APP_KEY = NyLVrF3aAt4BUJsnW8I7ag

# hostname for the LMS
# BETA
LMS_HOST = uwosh-beta.courses.wisconsin.edu
# PRODUCTION
#LMS_HOST = uwosh.courses.wisconsin.edu

# web app host
HOST = localhost

# web app port number
PORT = 5000

# protocol for user/web app interaction
SCHEME = HTTP

# port number for the LMS
LMS_PORT = 443

# If True, will use HTTPS
ENCRYPT_REQUESTS = True

# cert verification flag
VERIFY = False

# D2L component API versions to call (lp = learning platform, le = learning environment, ep = eportfolio)
LMS_VER = {'lp':1.3,'le':10.3,'ep':2.3}

# API version
VER = 1.4

# authorization route
AUTH_ROUTE = /request

# authorization callback route
# AUTH_CB = '{0}://{1}:{2}{3}'.format(SCHEME, HOST, PORT, AUTH_ROUTE)

# constants for API calls
# code for course in orgunits API route call
ORG_UNIT_TYPE_ID = 3

# additional email settings
EMAIL_DOMAIN = uwosh.edu
EMAIL_SITE_ADMIN = d2l@uwosh.edu

# redirect url following logout
REDIRECT_AFTER_LOGOUT = http://www.uwosh.edu/d2lfaq/d2l-login/

# By default, the toolbar only appears for clients from IP addresses
# '127.0.0.1' and '::1'.
# debugtoolbar.hosts = 127.0.0.1 ::1

###
# wsgi server configuration
###

[server:main]
use = egg:waitress#main
host = 0.0.0.0
port = 5000
# waitress--for use behind reverse proxy server
#url_scheme = https

###
# logging configuration
# http://docs.pylonsproject.org/projects/pyramid/en/1.5-branch/narr/logging.html
###

[loggers]
keys = root, camtasia_request

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console

[logger_camtasia_request]
level = DEBUG
handlers =
qualname = camtasia_request

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s][%(threadName)s] %(message)s
